server:
  port: 9096
spring:
  application:
    name: JRTP-Correspondence_API-07
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Tara
    url: jdbc:mysql://localhost:3306/userdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: taraprasadjena40@gmail.com
    password: ntjgsclgoehbogex
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectionTimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    com.co.utils.EmailUtils: DEBUG
    org.springframework.mail: DEBUG
